logging:
#  level:
#    org.springframework.security: info
#    org.springframework.boot: DEBUG
#    org.springframework.orm.jpa: DEBUG
#    org.hibernate: DEBUG
  level:
    root: ERROR
    org.springframework: WARN
    org.hibernate: ERROR



spring:
  security:
    oauth2:
      client:
        registration:
          github:
            # Make sure to put your client ID/secret from GitHub ;)
            client-id: Ov23lilDrBGI9EfIZuop
            client-secret: 3a09bb97619f177effc2e1cb0c3e20d98fc8202b
            redirect-uri: "http://localhost:8080/login/oauth2/code/github"
            scope: read:user
            client-name: GitHub
            authorization-grant-type: authorization_code
        provider:
          github:
            token-uri: https://github.com/login/oauth/access_token
            authorization-uri: https://github.com/login/oauth/authorize
            user-info-uri: https://api.github.com/user

  docker:
    compose:
      file: .\docker-compose.yml


# if the code doesn't work on port 8080 uncomint this two line code
#  server:
#      port: 9090  # Change this to your desired port


# this part of the code is still under working for the Repository

  datasource:
    type: com.zaxxer.hikari.HikariDataSource # Example: HikariCP (default)
    url: jdbc:postgresql://localhost:5432/exambytedatabase
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate schema auto-creation since Flyway is used
    show-sql: true   # Enable to see SQL queries in the logs
    properties:
      hibernate:
        format_sql: true # Format SQL output in logs

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    ignore-unsupported-database: true

server:
  error:
    whitelabel:
      enabled: false        # Disable Spring Boot's default Whitelabel error page
    path: /error            # The default error path
    include-message: always # Include the error message in responses (optional)
    include-stacktrace: on-param # Show stack trace only if `trace=true` in query params
