ALTER TABLE tests ALTER COLUMN start_time SET NOT NULL;
ALTER TABLE tests ALTER COLUMN end_time SET NOT NULL;
ALTER TABLE tests ALTER COLUMN result_publication_time SET NOT NULL;
ALTER TABLE tests ALTER COLUMN created_by SET NOT NULL;
